### ISSUE TITLE
Suggestion: provide as first value to entry the free text

### ISSUE THREAD

**Issue by llrs** [politicalwatch/tipiciudadano.es#2]
Many thanks for providing this tool! I wanted to do something like this since I started using the BOE API!

I think it would gain a lot of usability if users could easily search by text by simply start writing and pressing Enter. Currently on Firefox this doesn't work and one needs to go to advanced search to find the free text search field.

----
Unrelated to this question/issue but it would be possible to extract the history of each proposal so to know when one can do "enmiendas" to the proposal?

**Comment by pr3ssh** [comment]
Thank you @llrs for your issue/question/suggestion. It's very nice to receive community feedback.
At the beginning of the project, we invest a lot of time thinking about what would be the best way to show search fields to users and finally we decide the current setup, due our topics-focused tool.

---

I have a doubt: what kind of feature doesn't work on Firefox?

---

I suggest you to use our [API](https://api.tipiciudadano.es) for building your own interface. Have you got the knowledge to do this? It would be a great news.

---

Many thanks!

**Comment by llrs** [comment]
Ok, I just thought this would be easier for people but you have your motives and reasons to do so and it is still possible :smile: .  

About the problem: If I prepare a search with some terms and dates and press Enter on the keyboard the website wouldn't react and search. I needed to use the mouse. Is the website just tested on Chrome? 

I could build my own interface and website but I'm not willing to pay a server for this hobby project at the moment. 

Thanks for your quick reply and all the best wishes to this project!

**Comment by pr3ssh** [comment]
@llrs You could use [Netlify free plan](https://www.netlify.com/pricing/) to host your webapp.

You are right! The _press-enter-on-form-and-submit_ funcionality is not implemented yet. We get to it.

**Comment by llrs** [comment]
I thought that Netlify didn't offer any free reactive plan (i.e. only static websites) but it seems that it offers "dynamic serverless functions"... will look into this. Thanks for the nudge!

**Comment by pr3ssh** [comment]
Really you just need static website with some JS funcionality (called for them JAMstack). You can deploy freely a Vue app for that. Hope it helps.
